(()=>{const sb=window.supabaseClient,$=id=>document.getElementById(id);let user=null,profile={};
function showView(id,button){document.querySelectorAll(".view").forEach(x=>{x.classList.remove("active");x.style.display="none"});document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));const v=$(id);if(v){v.classList.add("active");v.style.display="block";v.scrollIntoView({block:"start",behavior:"smooth"})}if(button)button.classList.add("active");}
window.ASTRA_SHOW_VIEW=showView;
const signs=["Capricórnio","Aquário","Peixes","Carneiro","Touro","Gémeos","Caranguejo","Leão","Virgem","Balança","Escorpião","Sagitário"];
function solar(date){if(!date)return "—";let d=new Date(date+"T12:00:00"),m=d.getMonth()+1,day=d.getDate(),cuts=[[1,20,"Capricórnio","Aquário"],[2,19,"Aquário","Peixes"],[3,21,"Peixes","Carneiro"],[4,20,"Carneiro","Touro"],[5,21,"Touro","Gémeos"],[6,21,"Gémeos","Caranguejo"],[7,23,"Caranguejo","Leão"],[8,23,"Leão","Virgem"],[9,23,"Virgem","Balança"],[10,23,"Balança","Escorpião"],[11,22,"Escorpião","Sagitário"],[12,22,"Sagitário","Capricórnio"]],x=cuts[m-1];return day<x[1]?x[2]:x[3]}
function paintProfile(){if(!user)return;$("greeting").textContent="Olá"+(profile.full_name?" "+profile.full_name.split(" ")[0]:"")+" ✦";$("todayDate").textContent=new Intl.DateTimeFormat("pt-PT",{dateStyle:"full"}).format(new Date());$("pName").textContent=profile.full_name||"—";$("pEmail").textContent=user.email||"—";$("pBirth").textContent=profile.birth_date||"—";$("pPlan").textContent=profile.plan==="premium"?"Premium":"Free";$("editName").value=profile.full_name||"";$("editBirth").value=profile.birth_date||"";$("editTime").value=profile.birth_time||"";$("editPlace").value=profile.birth_place||"";$("editTimezone").value=profile.birth_timezone||"";$("sunSign").textContent=solar(profile.birth_date);$("moonSign").textContent=profile.moon_sign||"Por calcular";$("ascSign").textContent=profile.ascendant_sign||"Por calcular";$("descSign").textContent=profile.descendant_sign||"Por calcular";}
async function load(){
 let sessionResult=await sb.auth.getSession(),session=sessionResult.data?.session||null;
 if(!session){const refreshed=await sb.auth.refreshSession();session=refreshed.data?.session||null}
 if(!session?.user){location.replace("index.html");return}
 user=session.user;
 const verified=await sb.auth.getUser();
 if(verified.data?.user)user=verified.data.user;
 let q=await sb.from("profiles").select("*").eq("id",user.id).single();if(q.error){console.error("profile load",q.error);profile={};}else profile=q.data||{};
 paintProfile();document.body.dataset.appReady="true";
 if(window.ASTRA_ENTITLEMENTS)await ASTRA_ENTITLEMENTS.refresh(sb);await restoreDaily();
 let placeFix=window.ASTRA_PLACES?.resolve?.(profile.birth_place||"");if(placeFix&&(!profile.birth_lat||!profile.birth_lon)){const geo={birth_lat:placeFix.lat,birth_lon:placeFix.lon,birth_timezone:profile.birth_timezone||placeFix.timezone,updated_at:new Date().toISOString()};const gz=await sb.from("profiles").update(geo).eq("id",user.id);if(!gz.error)profile={...profile,...geo};}
 const ready=window.ASTRA_ASTRO?.birthDataReady?.(profile);if(!ready){setTimeout(()=>{$("editName").value=profile.full_name||"";$("editBirth").value=profile.birth_date||"";$("editTime").value=profile.birth_time||"";$("editPlace").value=profile.birth_place||"";$("editTimezone").value=profile.birth_timezone||"";$("profileMsg").textContent="Completa os teus dados de nascimento para criar o teu perfil ASTRA.";$("profileDialog").showModal()},150)}else if((!profile.moon_sign||!profile.ascendant_sign||!profile.descendant_sign)&&window.ASTRA_NATAL?.calculateNatal){try{let r=await ASTRA_NATAL.calculateNatal(profile),astro={moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()};await sb.from("profiles").update(astro).eq("id",user.id);profile={...profile,...astro};$("moonSign").textContent=r.moon.name;$("ascSign").textContent=r.ascendant.name;$("descSign").textContent=r.descendant.name;window.ASTRA_LAST_NATAL=r;window.ASTRA_RENDER_NATAL?.(r);$("chartStatus").textContent="Mapa calculado com os teus dados de nascimento."}catch(e){console.warn("automatic natal calculation",e)}}
}
document.addEventListener("click",e=>{const b=e.target.closest(".nav[data-view]");if(b){e.preventDefault();showView(b.dataset.view,b)}});
$("logout").onclick=async()=>{await sb.auth.signOut();location.href="index.html"};
$("editProfile").onclick=()=>{paintProfile();const d=$("profileDialog");if(d.showModal)d.showModal();else d.setAttribute("open","")};
$("closeProfile").onclick=()=>$("profileDialog").close();
$("editPlace").addEventListener("change",()=>{let r=window.ASTRA_PLACES?.resolve?.($("editPlace").value);$("placeResolved").textContent=r?`${r.name} · ${r.lat.toFixed(4)}, ${r.lon.toFixed(4)} · ${r.timezone}`:"Local não encontrado na lista offline.";if(r)$("editTimezone").value=r.timezone});
$("saveProfile").onclick=async()=>{if(!user||!profile?.id){$("profileMsg").textContent="O perfil ainda está a carregar. Tenta novamente dentro de instantes.";return}let name=$("editName").value.trim(),birth=$("editBirth").value;if(!name||!birth){$("profileMsg").textContent="Nome e data de nascimento são obrigatórios.";return}let r=window.ASTRA_PLACES?.resolve?.($("editPlace").value),patch={full_name:name,birth_date:birth,birth_time:$("editTime").value||profile.birth_time||null,birth_place:$("editPlace").value.trim()||profile.birth_place||"",birth_timezone:$("editTimezone").value||profile.birth_timezone||null,updated_at:new Date().toISOString()};if(r){patch.birth_lat=r.lat;patch.birth_lon=r.lon}let z=await sb.from("profiles").update(patch).eq("id",user.id);$("profileMsg").textContent=z.error?z.error.message:"Guardado.";if(!z.error){profile={...profile,...patch};try{if(window.ASTRA_ASTRO?.birthDataReady?.(profile)&&window.ASTRA_NATAL?.calculateNatal){let r=await ASTRA_NATAL.calculateNatal(profile),astro={moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()};await sb.from("profiles").update(astro).eq("id",user.id);profile={...profile,...astro}}catch(e){console.warn("natal profile calculation",e)}setTimeout(()=>location.reload(),500)}};
$("calculateChart").onclick=async()=>{let st=$("chartStatus");try{if(!window.ASTRA_NATAL?.calculateNatal){st.textContent="O motor astrológico ainda está a carregar. Tenta novamente dentro de instantes.";return}st.textContent="A calcular o teu céu natal…";let r=await window.ASTRA_NATAL.calculateNatal(profile);$("natalDetails").classList.remove("hidden");window.ASTRA_LAST_NATAL=r;window.ASTRA_RENDER_NATAL(r);$("moonSign").textContent=r.moon.name;$("ascSign").textContent=r.ascendant.name;$("descSign").textContent=r.descendant.name;await sb.from("profiles").update({moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()}).eq("id",user.id);st.textContent="Mapa calculado com os teus dados de nascimento."}catch(e){console.error(e);st.textContent=e.message==="BIRTH_DATA_INCOMPLETE"?"Completa data, hora, local e fuso horário no Perfil.":"Não foi possível calcular o mapa. Verifica os dados e a ligação."}};
function dailyCopy(){
 let seed=(profile.birth_date||"astra")+new Date().toISOString().slice(0,10),n=[...seed].reduce((a,c)=>a+c.charCodeAt(0),0),pick=(arr,k)=>arr[(n+k)%arr.length],L=window.ASTRA_I18N?.language||"pt";
 let all={pt:{love:["Hoje favorece conversas sinceras e gestos simples. Valoriza quem está ao teu lado e expressa o que sentes. Pequenos gestos podem fortalecer as tuas relações.","O afeto pede calma e presença. Dá espaço para ouvir antes de reagir. Uma conversa tranquila pode trazer maior proximidade.","Há uma energia favorável para fortalecer laços. Demonstra interesse através de atitudes concretas. Procura equilíbrio entre dar e receber."],work:["Define uma prioridade e avança passo a passo. Evita tentar resolver tudo ao mesmo tempo. A consistência pode trazer melhores resultados do que a pressa.","A organização vale mais hoje do que a velocidade. Concentra-te numa tarefa importante antes de começares outra. Revê os detalhes antes do próximo passo.","Uma ideia prática pode desbloquear algo que estava parado. Transforma-a numa ação concreta e mantém o foco. O progresso pode surgir de pequenas decisões."],well:["Reserva alguns minutos para abrandar o ritmo. Cuida do teu equilíbrio físico e mental ao longo do dia. Pequenas pausas podem ajudar-te a recuperar energia.","Procura equilíbrio entre movimento e descanso. Evita acumular tensão desnecessária e respeita o teu ritmo. Um momento de tranquilidade pode ajudar-te a reorganizar o dia.","Pequenas pausas podem ajudar-te a recuperar foco. Respira com calma e dá espaço à recuperação. Rotinas simples de bem-estar podem fazer diferença."]},en:{love:["Today favors honest conversations and simple gestures.","Give affection room without forcing answers.","A connection may become clearer if you listen before reacting."],work:["Choose one priority and finish it before opening another.","Organization matters more than speed today.","A practical idea may unlock something that was stuck."],well:["Take a few minutes to slow your pace.","Seek balance between movement and rest.","Small breaks may help you regain focus."]},es:{love:["Hoy favorece las conversaciones sinceras y los gestos simples.","Da espacio al afecto sin forzar respuestas.","Una conexión puede aclararse si escuchas antes de reaccionar."],work:["Elige una prioridad y termínala antes de empezar otra.","Hoy la organización vale más que la prisa.","Una idea práctica puede desbloquear algo estancado."],well:["Reserva unos minutos para bajar el ritmo.","Busca equilibrio entre movimiento y descanso.","Pequeñas pausas pueden ayudarte a recuperar el foco."]}},R=all[L]||all.pt;
 return{love:pick(R.love,1),work:pick(R.work,2),well:pick(R.well,3),language:L}
}
function showDaily(r,status){$("dailyTexts").innerHTML=`<h3>❤️ Amor</h3><p>${r.love_text||r.love}</p><h3>💼 Trabalho</h3><p>${r.work_text||r.work}</p><h3>🌿 Bem-estar</h3><p>${r.wellbeing_text||r.well}</p>`;$("dailyResult").classList.remove("hidden");$("dailyStatus").textContent=status||"A tua leitura de hoje está guardada.";$("dailyBtn").textContent="Ver novamente a leitura de hoje"}
async function restoreDaily(){if(!user||window.ASTRA_ENTITLEMENTS?.isPremium?.())return;let q=await sb.from("daily_consultations").select("love_text,work_text,wellbeing_text,language").eq("user_id",user.id).eq("consultation_date",new Date().toISOString().slice(0,10)).eq("kind","free_daily").maybeSingle();if(q.data?.love_text)showDaily(q.data,"A tua consulta Free de hoje já foi realizada. Podes voltar a vê-la quando quiseres.")}
$("dailyBtn").onclick=async()=>{let b=$("dailyBtn"),s=$("dailyStatus");try{if(!user){s.textContent="A restaurar a tua sessão…";await load();if(!user)return}b.disabled=true;let premium=window.ASTRA_ENTITLEMENTS?.isPremium?.()||false,r=dailyCopy();if(premium){showDaily(r,"Premium · consultas sem limite");b.disabled=false;return}let q=await sb.rpc("save_daily_consultation",{p_love:r.love,p_work:r.work,p_wellbeing:r.well,p_language:r.language});if(q.error){s.textContent="Não foi possível guardar a consulta. Tenta novamente.";b.disabled=false;return}let saved=Array.isArray(q.data)?q.data[0]:q.data;if(saved)showDaily(saved,saved.created?"Consulta de hoje concluída.":"A tua leitura de hoje já estava guardada.");b.disabled=false}catch(e){console.error("daily reading",e);s.textContent="Não foi possível abrir a leitura. Tenta novamente.";b.disabled=false}};
sb.auth.onAuthStateChange((event,session)=>{
 if(event==="SIGNED_OUT"){location.replace("index.html");return}
 if((event==="TOKEN_REFRESHED"||event==="SIGNED_IN")&&session?.user&&(!user||user.id!==session.user.id)){user=session.user;load().catch(console.error)}
});
document.addEventListener("astra:natal-ready",()=>{if(profile?.birth_date&&window.ASTRA_ASTRO?.birthDataReady?.(profile)&&(!profile.moon_sign||!profile.ascendant_sign||!profile.descendant_sign))$("calculateChart")?.click()},{once:true});
load().catch(e=>{console.error("ASTRA startup",e);const m=document.getElementById("dailyStatus");if(m)m.textContent="Não foi possível restaurar a sessão. Tenta entrar novamente.";});
})();