(()=>{const sb=window.supabaseClient,$=id=>document.getElementById(id);let user=null,profile={};
function showView(id,button){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".nav").forEach(x=>x.classList.remove("active"));const v=$(id);if(v)v.classList.add("active");if(button)button.classList.add("active");}
window.ASTRA_SHOW_VIEW=showView;
const signs=["Capricórnio","Aquário","Peixes","Carneiro","Touro","Gémeos","Caranguejo","Leão","Virgem","Balança","Escorpião","Sagitário"];
function solar(date){if(!date)return "—";let d=new Date(date+"T12:00:00"),m=d.getMonth()+1,day=d.getDate(),cuts=[[1,20,"Capricórnio","Aquário"],[2,19,"Aquário","Peixes"],[3,21,"Peixes","Carneiro"],[4,20,"Carneiro","Touro"],[5,21,"Touro","Gémeos"],[6,21,"Gémeos","Caranguejo"],[7,23,"Caranguejo","Leão"],[8,23,"Leão","Virgem"],[9,23,"Virgem","Balança"],[10,23,"Balança","Escorpião"],[11,22,"Escorpião","Sagitário"],[12,22,"Sagitário","Capricórnio"]],x=cuts[m-1];return day<x[1]?x[2]:x[3]}
function paintProfile(){if(!user)return;$("greeting").textContent="Olá"+(profile.full_name?" "+profile.full_name.split(" ")[0]:"")+" ✦";$("todayDate").textContent=new Intl.DateTimeFormat("pt-PT",{dateStyle:"full"}).format(new Date());$("pName").textContent=profile.full_name||"—";$("pEmail").textContent=user.email||"—";$("pBirth").textContent=profile.birth_date||"—";$("pPlan").textContent=profile.plan==="premium"?"Premium":"Free";$("editName").value=profile.full_name||"";$("editBirth").value=profile.birth_date||"";$("editTime").value=profile.birth_time||"";$("editPlace").value=profile.birth_place||"";$("editTimezone").value=profile.birth_timezone||"";$("sunSign").textContent=solar(profile.birth_date);$("moonSign").textContent=profile.moon_sign||"Por calcular";$("ascSign").textContent=profile.ascendant_sign||"Por calcular";$("descSign").textContent=profile.descendant_sign||"Por calcular";}
async function load(){
 let x=await sb.auth.getUser();user=x.data.user;if(!user){location.href="index.html";return}
 let q=await sb.from("profiles").select("*").eq("id",user.id).single();if(q.error){console.error("profile load",q.error);profile={};}else profile=q.data||{};
 paintProfile();
 if(window.ASTRA_ENTITLEMENTS)await ASTRA_ENTITLEMENTS.refresh(sb);
 let placeFix=window.ASTRA_PLACES?.resolve?.(profile.birth_place||"");if(placeFix&&(!profile.birth_lat||!profile.birth_lon)){const geo={birth_lat:placeFix.lat,birth_lon:placeFix.lon,birth_timezone:profile.birth_timezone||placeFix.timezone,updated_at:new Date().toISOString()};const gz=await sb.from("profiles").update(geo).eq("id",user.id);if(!gz.error)profile={...profile,...geo};}
 const ready=window.ASTRA_ASTRO?.birthDataReady?.(profile);if(!ready){setTimeout(()=>{$("editName").value=profile.full_name||"";$("editBirth").value=profile.birth_date||"";$("editTime").value=profile.birth_time||"";$("editPlace").value=profile.birth_place||"";$("editTimezone").value=profile.birth_timezone||"";$("profileMsg").textContent="Completa os teus dados de nascimento para criar o teu perfil ASTRA.";$("profileDialog").showModal()},150)}else if((!profile.moon_sign||!profile.ascendant_sign||!profile.descendant_sign)&&window.ASTRA_NATAL?.calculateNatal){try{let r=await ASTRA_NATAL.calculateNatal(profile),astro={moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()};await sb.from("profiles").update(astro).eq("id",user.id);profile={...profile,...astro};$("moonSign").textContent=r.moon.name;$("ascSign").textContent=r.ascendant.name;$("descSign").textContent=r.descendant.name;window.ASTRA_LAST_NATAL=r;window.ASTRA_RENDER_NATAL?.(r);$("chartStatus").textContent="Mapa calculado com os teus dados de nascimento."}catch(e){console.warn("automatic natal calculation",e)}}
}
document.addEventListener("click",e=>{const b=e.target.closest(".nav[data-view]");if(b){e.preventDefault();showView(b.dataset.view,b)}});
$("logout").onclick=async()=>{await sb.auth.signOut();location.href="index.html"};
$("editProfile").onclick=()=>{paintProfile();const d=$("profileDialog");if(d.showModal)d.showModal();else d.setAttribute("open","")};
$("closeProfile").onclick=()=>$("profileDialog").close();
$("editPlace").addEventListener("change",()=>{let r=window.ASTRA_PLACES?.resolve?.($("editPlace").value);$("placeResolved").textContent=r?`${r.name} · ${r.lat.toFixed(4)}, ${r.lon.toFixed(4)} · ${r.timezone}`:"Local não encontrado na lista offline.";if(r)$("editTimezone").value=r.timezone});
$("saveProfile").onclick=async()=>{let r=window.ASTRA_PLACES?.resolve?.($("editPlace").value),patch={full_name:$("editName").value.trim(),birth_date:$("editBirth").value||null,birth_time:$("editTime").value||null,birth_place:$("editPlace").value.trim(),birth_timezone:$("editTimezone").value||null,updated_at:new Date().toISOString()};if(r){patch.birth_lat=r.lat;patch.birth_lon=r.lon}let z=await sb.from("profiles").update(patch).eq("id",user.id);$("profileMsg").textContent=z.error?z.error.message:"Guardado.";if(!z.error){profile={...profile,...patch};try{if(window.ASTRA_ASTRO?.birthDataReady?.(profile)&&window.ASTRA_NATAL?.calculateNatal){let r=await ASTRA_NATAL.calculateNatal(profile),astro={moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()};await sb.from("profiles").update(astro).eq("id",user.id);profile={...profile,...astro}}catch(e){console.warn("natal profile calculation",e)}setTimeout(()=>location.reload(),500)}};
$("calculateChart").onclick=async()=>{let st=$("chartStatus");try{st.textContent="A calcular o teu céu natal…";let r=await window.ASTRA_NATAL.calculateNatal(profile);$("natalDetails").classList.remove("hidden");window.ASTRA_LAST_NATAL=r;window.ASTRA_RENDER_NATAL(r);$("moonSign").textContent=r.moon.name;$("ascSign").textContent=r.ascendant.name;$("descSign").textContent=r.descendant.name;await sb.from("profiles").update({moon_sign:r.moon.name,ascendant_sign:r.ascendant.name,descendant_sign:r.descendant.name,updated_at:new Date().toISOString()}).eq("id",user.id);st.textContent="Mapa calculado com os teus dados de nascimento."}catch(e){console.error(e);st.textContent=e.message==="BIRTH_DATA_INCOMPLETE"?"Completa data, hora, local e fuso horário no Perfil.":"Não foi possível calcular o mapa. Verifica os dados e a ligação."}};
$("dailyBtn").onclick=async()=>{let b=$("dailyBtn"),s=$("dailyStatus");b.disabled=true;let premium=window.ASTRA_ENTITLEMENTS?.isPremium?.()||false;if(!premium){let q=await sb.rpc("claim_daily_consultation");if(q.error){s.textContent="Não foi possível validar a consulta.";b.disabled=false;return}if(!q.data){s.textContent="A tua consulta Free de hoje já foi utilizada. Volta amanhã 🌙";b.textContent="Volta amanhã 🌙";return}}
 let seed=(profile.birth_date||"astra")+new Date().toISOString().slice(0,10),n=[...seed].reduce((a,c)=>a+c.charCodeAt(0),0),pick=(arr,k)=>arr[(n+k)%arr.length];
 let L=window.ASTRA_I18N?.language||"pt",all={pt:{love:["Hoje favorece conversas sinceras e gestos simples. Valoriza quem está ao teu lado e expressa o que sentes. Pequenos gestos podem fortalecer as tuas relações.","O afeto pede calma e presença. Dá espaço para ouvir antes de reagir. Uma conversa tranquila pode trazer maior proximidade.","Há uma energia favorável para fortalecer laços. Demonstra interesse através de atitudes concretas. Procura equilíbrio entre dar e receber."],work:["Define uma prioridade e avança passo a passo. Evita tentar resolver tudo ao mesmo tempo. A consistência pode trazer melhores resultados do que a pressa.","A organização vale mais hoje do que a velocidade. Concentra-te numa tarefa importante antes de começares outra. Revê os detalhes antes do próximo passo.","Uma ideia prática pode desbloquear algo que estava parado. Transforma-a numa ação concreta e mantém o foco. O progresso pode surgir de pequenas decisões."],well:["Reserva alguns minutos para abrandar o ritmo. Cuida do teu equilíbrio físico e mental ao longo do dia. Pequenas pausas podem ajudar-te a recuperar energia.","Procura equilíbrio entre movimento e descanso. Evita acumular tensão desnecessária e respeita o teu ritmo. Um momento de tranquilidade pode ajudar-te a reorganizar o dia.","Pequenas pausas podem ajudar-te a recuperar foco. Respira com calma e dá espaço à recuperação. Rotinas simples de bem-estar podem fazer diferença."]},en:{love:["Today favors honest conversations and simple gestures.","Give affection room without forcing answers.","A connection may become clearer if you listen before reacting."],work:["Choose one priority and finish it before opening another.","Organization matters more than speed today.","A practical idea may unlock something that was stuck."],well:["Take a few minutes to slow your pace.","Seek balance between movement and rest.","Small breaks may help you regain focus."]},es:{love:["Hoy favorece las conversaciones sinceras y los gestos simples.","Da espacio al afecto sin forzar respuestas.","Una conexión puede aclararse si escuchas antes de reaccionar."],work:["Elige una prioridad y termínala antes de empezar otra.","Hoy la organización vale más que la prisa.","Una idea práctica puede desbloquear algo estancado."],well:["Reserva unos minutos para bajar el ritmo.","Busca equilibrio entre movimiento y descanso.","Pequeñas pausas pueden ayudarte a recuperar el foco."]}},R=all[L]||all.pt,love=R.love,work=R.work,well=R.well;
 $("dailyTexts").innerHTML=`<h3>❤️ Amor</h3><p>${pick(love,1)}</p><h3>💼 Trabalho</h3><p>${pick(work,2)}</p><h3>🌿 Bem-estar</h3><p>${pick(well,3)}</p>`;$("dailyResult").classList.remove("hidden");s.textContent=premium?"Premium · consultas sem limite":"Consulta de hoje concluída.";b.disabled=false};
load();
})();