(()=>{const D={
pt:{lang:"Português",accountTitle:"Cria a tua Conta Astralis",accountInfo:"Cria uma conta gratuita e recebe a tua consulta diária Astralis. Tens 1 consulta grátis por dia e, quando quiseres, podes avançar para o Premium para desbloquear o mapa astral e leituras mais completas.",freeDaily:"1 consulta gratuita por dia",freeOptional:"Cria a tua conta sem custos. O Premium é opcional.",discover:"Descobre o teu dia ✦",intro:"O céu muda todos os dias. A tua energia também.",fullName:"Nome completo",namePH:"Nome e apelido",birth:"Data de nascimento",continue:"Continuar ✨",account:"Conta Astralis",loginTitle:"Entrar na Conta Astralis",email:"Email",password:"Password",enter:"Entrar",noAccount:"Ainda não tens conta?",create:"Criar conta",createTitle:"Criar conta ✦",createInfo:"Cria a tua conta para guardar o teu perfil e as tuas leituras.",confirmPassword:"Confirmar password",repeatPassword:"Repete a password",createButton:"Criar conta",premium:"Astralis Premium",perMonth:"/ mês",logout:"Terminar sessão",today:"Hoje",chart:"Mapa",profile:"Perfil",love:"Amor",work:"Trabalho",well:"Saúde & bem-estar"},
en:{lang:"English",accountTitle:"Create your Astralis Account",accountInfo:"Create a free account and receive your daily Astralis reading. You get 1 free reading per day and can upgrade to Premium whenever you want to unlock your birth chart and more complete readings.",freeDaily:"1 free reading per day",freeOptional:"Create your account at no cost. Premium is optional.",discover:"Discover your day ✦",intro:"The sky changes every day. So does your energy.",fullName:"Full name",namePH:"First and last name",birth:"Date of birth",continue:"Continue ✨",account:"Astralis Account",loginTitle:"Sign in to your Astralis Account",email:"Email",password:"Password",enter:"Sign in",noAccount:"Don't have an account yet?",create:"Create account",createTitle:"Create account ✦",createInfo:"Create your account to save your profile and readings.",confirmPassword:"Confirm password",repeatPassword:"Repeat password",createButton:"Create account",premium:"Astralis Premium",perMonth:"/ month",logout:"Sign out",today:"Today",chart:"Chart",profile:"Profile",love:"Love",work:"Work",well:"Health & wellbeing"},
es:{lang:"Español",accountTitle:"Crea tu Cuenta Astralis",accountInfo:"Crea una cuenta gratuita y recibe tu consulta diaria Astralis. Tienes 1 consulta gratis al día y puedes pasar a Premium cuando quieras para desbloquear tu carta astral y lecturas más completas.",freeDaily:"1 consulta gratuita al día",freeOptional:"Crea tu cuenta sin coste. Premium es opcional.",discover:"Descubre tu día ✦",intro:"El cielo cambia cada día. Tu energía también.",fullName:"Nombre completo",namePH:"Nombre y apellido",birth:"Fecha de nacimiento",continue:"Continuar ✨",account:"Cuenta Astralis",loginTitle:"Entrar en tu Cuenta Astralis",email:"Email",password:"Contraseña",enter:"Entrar",noAccount:"¿Aún no tienes cuenta?",create:"Crear cuenta",createTitle:"Crear cuenta ✦",createInfo:"Crea tu cuenta para guardar tu perfil y tus lecturas.",confirmPassword:"Confirmar contraseña",repeatPassword:"Repite la contraseña",createButton:"Crear cuenta",premium:"Astralis Premium",perMonth:"/ mes",logout:"Cerrar sesión",today:"Hoy",chart:"Carta",profile:"Perfil",love:"Amor",work:"Trabajo",well:"Salud y bienestar"}};
let lang=localStorage.getItem("astra_language")||"pt";if(!D[lang])lang="pt";
function t(k){return D[lang][k]||D.pt[k]||k}
function apply(root=document){document.documentElement.lang=lang;root.querySelectorAll("[data-i18n]").forEach(e=>e.textContent=t(e.dataset.i18n));root.querySelectorAll("[data-i18n-placeholder]").forEach(e=>e.placeholder=t(e.dataset.i18nPlaceholder));root.querySelectorAll("[data-lang]").forEach(e=>e.classList.toggle("active",e.dataset.lang===lang));document.dispatchEvent(new CustomEvent("astra:language",{detail:{lang}}))}
function set(l){if(!D[l])return;lang=l;localStorage.setItem("astra_language",l);apply()}
window.ASTRA_I18N={t,set,apply,get language(){return lang},dictionary:D};
document.addEventListener("DOMContentLoaded",()=>{document.querySelectorAll("[data-lang]").forEach(b=>b.addEventListener("click",()=>set(b.dataset.lang)));apply()});
})();